### ISSUE TITLE
Running under PM2 & cluster mode

### ISSUE THREAD

**Issue by JonSilver** [jmservera/node-red-webapp#8]
Azure App Service has PM2 installed and enabled by default. Should we not be running node-red under PM2? And if so, couldn't we employ its clustering mode to give us an instance of node red on every core?

**Comment by jmservera** [comment]
Hi, thanks for the suggestion but this template deploys it under Windows using IISNode because when I created it there were no containers available yet, so this one cannot use PM2. I'm working on a Linux version, but if you want this now, I suggest you to use a containers enabled web app and deploy directly from: https://hub.docker.com/r/nodered/node-red
